def validator(guess):
    if guess>0:
        print('You have',guess,'guesses left')
    elif guess<=0:
        print('Game Over')
        return -1

a=50
print('--------------------->Rules<----------------------')
print('You have to guess a number in 10 attempts\n1.)Which will automatically generated by Our bot ')
print("Welcome to the Guess the game")
guesses=10
while(True):
    b=int(input('Enter a number\n'))
    guesses=guesses-1
    if a<b:
        print("Enter a Lower number",end=' ')
        if a>b:
            validator(guesses)
        if validator(guesses)==-1:
            break
    elif a>b:
        print("Enter a Greater number",end=' ')
        if a<b:
            validator(guesses)
        if validator(guesses)==-1:
            break
    elif a==b:
        print('----------------------------->Congratulations you guessed the number in',10-guesses,"guesses<-------------------------")
        print("Thank You for playing this game ! We will see you next time")
        break